services:
  #1. データベース（既製品）
  db:
    image: mysql:8
    container_name: my-memo-mysql-compose
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_memo_db
    ports:
      - "3307:3306" # 開発途中に直接SQLをのぞいたりするためにこのポートは開けておく
    volumes:
      - mysql-data-compose:/var/lib/mysql
  
  #2. バックエンド（自作）
  api:
    build: ./my-memo-api-docker  # dockerfileがあるフォルダを指定
    container_name: my-memo-api-container
    ports:
      - "8080:8080"
    depends_on:
      - db  # dbが先に起動するのを待つ
  
  #3. フロントエンド（自作）
  front:
    build: ./my-memo-front-docker # dockerfileがあるフォルダを指定
    container_name: my-memo-front-container
    ports:
      - "5173:5173"
    depends_on:
      - api # apiが先に起動するのを待つ

volumes:
  mysql-data-compose: