-- IDを指定せず、自動採番に任せる
INSERT INTO POSTS (TITLE, CONTENT, CREATED_AT) VALUES ('はじめての投稿', 'こんにちは！H2データベース。', CURRENT_TIMESTAMP);
INSERT INTO POSTS (TITLE, CONTENT, CREATED_AT) VALUES ('2番目のメモ', '自動投入は便利ですね。', CURRENT_TIMESTAMP);